### ISSUE TITLE
Tabs width not set on page load

### ISSUE THREAD

**Issue by AriLFrankel** [MerlinLabs/styled-material-components#120]
In order to correctly fill the space in which they are contained, the Tabs component relies on getBoundingClientRect in componentDidMount to calculate an appropriate tab width if none is passed in props. Until componentDidMount, the tabs do not have the appropriate width, then they snap to the correct width the first time that componentDidMount runs.

**Comment by hsarb** [comment]
Fixed by: https://github.com/MerlinLabs/styled-material-components/pull/200
