### ISSUE TITLE
ink-bar and nav items jelly-like

### ISSUE THREAD

**Issue by BennettStaley** [MerlinLabs/styled-material-components#177]
Because of the fact that the items in the nav might not all be the same size, the current implementation, while solving that issue, has created the effect where the ink bar snaps into the correct position when resizing the window.

This could obviously be improved, I'll add any findings on solutions here, and encourage others to add thoughts as well... !

**Comment by hsarb** [comment]
If this was specifically related to Tabs, should be fixed by: https://github.com/MerlinLabs/styled-material-components/pull/200

**Comment by BennettStaley** [comment]
Actually it was related to the navbar and items, which has since been reworked and renamed. But good catch on this, I'll close it now.
