### ISSUE TITLE
Create FloatingActionButton Component

### ISSUE THREAD

**Issue by martahj** [MerlinLabs/styled-material-components#18]
https://material.io/guidelines/components/buttons-floating-action-button.html

**Comment by rhiroy** [comment]
I am checking out this issue
![bitmoji](https://render.bitstrips.com/v2/cpanel/ff5bbaab-addc-439d-8088-a973db0bdfbb-713e5bad-2500-484a-9274-de1721302419-v1.png?transparent=1&palette=1&width=246)

**Comment by ashwoodall** [comment]
Hey @rhiroy, I'm going to submit a PR for this component since I need it for something I'm currently working on - but it's very MVP so feel free to add to it!
